var API_URL = 'https://script.google.com/macros/s/AKfycbz4UvN8c09Mv8ShudywG2YVp3E-mB1mwUUerT9EfhbJHHaFWDvWbxI_iLABoMZvhXkAKA/exec';
var ADMIN_PASSWORD = 'ralyne2026';
var videoData = [], hashtagData = [], funfactData = [], scheduleData = [], ticketData = [], faqData = [], suratData = [], galRalyneData = [], galRalvandraData = [];
var fanbaseData = { name: 'LibRaly', tagline: '', description: '', foundedDate: '', registrationOpen: false, registrationLink: '' };
var editingVId = null, editingHId = null, editingFfId = null, editingScId = null, editingTkId = null, editingFqId = null, editingGrId = null, editingGvId = null;
var activeCategoryScreen = null;
var batchGalType = '';
var TOXIC_WORDS = ['bodoh', 'goblok', 'anjing', 'bangsat', 'tolol', 'idiot', 'kontol', 'memek', 'ngentod', 'bgst', 'bajingan', 'kampret', 'asu', 'ngentot', 'jembut', 'pepek', 'setan', 'keparat', 'brengsek', 'fuck', 'shit', 'damn', 'stupid', 'bitch'];
var TEMA_TYPES = ['vc', '2shoot', 'mg'];
var BULAN_ID = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni', 'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

var FM = { ralyne: [], ralvandra: [] };
var FM_LOOKUP = {};
['ralyne', 'ralvandra'].forEach(function (c) { FM[c].forEach(function (f) { FM_LOOKUP[c + ':::' + f.key] = f }) });

function escHtml(s) { return String(s || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;') }
function escAttr(s) { return String(s || '').replace(/&/g, '&amp;').replace(/"/g, '&quot;').replace(/'/g, '&#39;').replace(/</g, '&lt;').replace(/>/g, '&gt;') }
function escJS(s) { return String(s || '').replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/"/g, '\\"') }
function isToxic(t) { if (!t) return false; var l = t.toLowerCase(); return TOXIC_WORDS.some(function (w) { return l.indexOf(w) !== -1 }) }
function toast(msg, type) { var t = document.createElement('div'); t.className = 'toast ' + (type || 'success'); t.textContent = msg; document.getElementById('toastBox').appendChild(t); setTimeout(function () { t.classList.add('show') }, 30); setTimeout(function () { t.classList.remove('show'); setTimeout(function () { t.remove() }, 400) }, 3500) }
function todayStr() { var t = new Date(); return t.getFullYear() + '-' + String(t.getMonth() + 1).padStart(2, '0') + '-' + String(t.getDate()).padStart(2, '0') }
function toIDDate(s) { if (!s) return ''; var p = s.split('-'); return parseInt(p[2], 10) + ' ' + BULAN_ID[parseInt(p[1], 10) - 1] + ' ' + p[0] }
function fromIDDate(s) { var M = { januari: '01', februari: '02', maret: '03', april: '04', mei: '05', juni: '06', juli: '07', agustus: '08', september: '09', oktober: '10', november: '11', desember: '12' }; var p = s.toLowerCase().replace(/[^a-z0-9\s]/g, '').trim().split(/\s+/); if (p.length < 3) return ''; return p[2] + '-' + (M[p[1]] || '01') + '-' + p[0].padStart(2, '0') }
function isTemaType(t) { return TEMA_TYPES.indexOf(t) !== -1 }
function tipeClass(t) { if (t === '2shoot') return 'two-shoot'; return t }
function tipeLabel(t) { var m = { theater: 'Theater', event: 'Event', digital: 'Digital', concert: 'Concert', offair: 'Off Air', vc: 'VC', '2shoot': '2Shoot', mg: 'M&G' }; return m[t] || t }
function platformClass(p) { var m = { 'YouTube': 'youtube', 'TikTok': 'tiktok', 'Instagram': 'instagram', 'X (Twitter)': 'x-twitter', 'Facebook': 'facebook', 'Lainnya': 'lainnya' }; return m[p] || 'lainnya' }

function apiGet(a) { return fetch(API_URL + '?action=' + a + '&t=' + Date.now(), { redirect: 'follow' }).then(function (r) { return r.json() }).catch(function () { return [] }) }
function apiPost(d) { return fetch(API_URL, { method: 'POST', headers: { 'Content-Type': 'text/plain;charset=utf-8' }, body: JSON.stringify(d), redirect: 'follow' }).then(function (r) { return r.text().then(function (t) { try { return JSON.parse(t) } catch (e) { return { success: true } } }) }).catch(function () { return { success: true } }) }

var eyeBtn = document.getElementById('loginEye'), passInput = document.getElementById('loginPass');
eyeBtn.addEventListener('click', function () { var h = passInput.type === 'password'; passInput.type = h ? 'text' : 'password'; eyeBtn.classList.toggle('active', h) });
document.getElementById('loginBtn').addEventListener('click', doLogin);
passInput.addEventListener('keydown', function (e) { if (e.key === 'Enter') doLogin() });
function doLogin() { if (passInput.value === ADMIN_PASSWORD) { sessionStorage.setItem('lr_auth', '1'); showDashboard() } else { document.getElementById('loginError').textContent = 'Password salah!' } }
function logout() { sessionStorage.removeItem('lr_auth'); document.getElementById('dashboardScreen').style.display = 'none'; document.querySelectorAll('.section-screen').forEach(function (el) { el.style.display = 'none' }); document.getElementById('loginGate').style.display = 'flex'; passInput.value = ''; passInput.type = 'password'; eyeBtn.classList.remove('active'); document.getElementById('loginError').textContent = ''; activeCategoryScreen = null }
if (sessionStorage.getItem('lr_auth') === '1') showDashboard();

function showDashboard() { document.getElementById('loginGate').style.display = 'none'; document.getElementById('dashboardScreen').style.display = 'block'; document.querySelectorAll('.section-screen').forEach(function (el) { el.style.display = 'none' }); activeCategoryScreen = null; refreshAll() }
function openCategory(id) { document.getElementById('dashboardScreen').style.display = 'none'; var m = { konten: 'categoryKonten', jadwal: 'categoryJadwal', galeri: 'categoryGaleri', fanbase: 'categoryFanbase' }; var el = document.getElementById(m[id]); if (el) { el.style.display = 'block'; activeCategoryScreen = m[id] } }
function openSection(s) { if (activeCategoryScreen) document.getElementById(activeCategoryScreen).style.display = 'none'; var m = { video: 'sectionVideo', hashtag: 'sectionHashtag', funfact: 'sectionFunfact', schedule: 'sectionSchedule', ticket: 'sectionTicket', galralyne: 'sectionGalralyne', galralvandra: 'sectionGalralvandra', profil: 'sectionProfil', faq: 'sectionFaq', pendaftaran: 'sectionPendaftaran', surat: 'sectionSurat' }; var el = document.getElementById(m[s]); if (el) el.style.display = 'block' }
function goToDashboard() { document.querySelectorAll('.section-screen').forEach(function (el) { el.style.display = 'none' }); document.getElementById('dashboardScreen').style.display = 'block'; activeCategoryScreen = null; updateDashboardCounts() }
function goBackToCategory() { document.querySelectorAll('.section-screen').forEach(function (el) { el.style.display = 'none' }); if (activeCategoryScreen) { document.getElementById(activeCategoryScreen).style.display = 'block' } else goToDashboard() }

function updateDashboardCounts() {
    var el;
    el = document.getElementById('dashVideoTotal'); if (el) el.textContent = videoData.length;
    el = document.getElementById('dashHashtagTotal'); if (el) el.textContent = hashtagData.length;
    el = document.getElementById('dashFunfactTotal'); if (el) el.textContent = funfactData.length;
    el = document.getElementById('dashScheduleTotal'); if (el) el.textContent = scheduleData.length;
    el = document.getElementById('dashTicketTotal'); if (el) el.textContent = ticketData.length;
    el = document.getElementById('dashGalRalyneTotal'); if (el) el.textContent = countGalPhotos(galRalyneData);
    el = document.getElementById('dashGalRalvandraTotal'); if (el) el.textContent = countGalPhotos(galRalvandraData);
    el = document.getElementById('dashGaleriTotal'); if (el) el.textContent = countGalPhotos(galRalyneData) + countGalPhotos(galRalvandraData);
    el = document.getElementById('dashFaqTotal'); if (el) el.textContent = faqData.length;
    el = document.getElementById('dashSuratTotal'); if (el) el.textContent = suratData.length;
    el = document.getElementById('dashSuratToxic'); if (el) el.textContent = suratData.filter(function (r) { return isToxic(r.pesan || r.message) }).length;
    el = document.getElementById('dashDaftarStatus'); if (el) { el.textContent = fanbaseData.registrationOpen ? 'Buka' : 'Tutup'; el.style.color = fanbaseData.registrationOpen ? 'var(--green)' : 'var(--red)' }
}
function countGalPhotos(d) { var c = 0; d.forEach(function (f) { c += (f.images || []).length }); return c }

function refreshAll() { refreshVideo(); refreshHashtag(); refreshFunfact(); refreshSchedule(); refreshTicket(); refreshGalRalyne(); refreshGalRalvandra(); refreshFaq(); refreshSurat(); refreshFanbase() }

function openModal(id) { document.getElementById(id).classList.add('active') }
function closeModal(id) { document.getElementById(id).classList.remove('active') }
document.querySelectorAll('.modal-overlay').forEach(function (el) { el.addEventListener('click', function (e) { if (e.target === el) el.classList.remove('active') }) });
function openDelete(msg, onConfirm) { document.getElementById('deleteMsg').innerHTML = msg; var btn = document.getElementById('deleteConfirmBtn'); btn.textContent = 'Hapus'; btn.className = 'btn-confirm'; btn.disabled = false; btn.onclick = function () { if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menghapus...'; onConfirm(btn) }; openModal('deleteModal') }
function buildPgHTML(c, t, tot, s, e, pFn, sFn, ps) { if (!tot) return ''; var h = '<div class="pagination-bar"><div class="pagination-info">Menampilkan <strong>' + s + '</strong>-<strong>' + e + '</strong> dari <strong>' + tot + '</strong></div><div style="display:flex;align-items:center;gap:12px;flex-wrap:wrap"><div style="display:flex;align-items:center;gap:6px;font-size:.76rem;color:var(--muted)">Tampil:<select class="pg-size-select" onchange="' + sFn + '(parseInt(this.value))">';[10, 15, 25, 50].forEach(function (v) { h += '<option value="' + v + '"' + (v === ps ? ' selected' : '') + '>' + v + '</option>' }); h += '</select></div><div class="pagination-controls"><button class="pg-btn" onclick="' + pFn + '(' + (c - 1) + ')"' + (c <= 1 ? ' disabled' : '') + '><svg viewBox="0 0 24 24"><polyline points="15 18 9 12 15 6"/></svg></button>'; pgNums(c, t).forEach(function (p) { if (p === '...') h += '<span class="pg-ellipsis">...</span>'; else h += '<button class="pg-btn' + (p === c ? ' active' : '') + '" onclick="' + pFn + '(' + p + ')">' + p + '</button>' }); h += '<button class="pg-btn" onclick="' + pFn + '(' + (c + 1) + ')"' + (c >= t ? ' disabled' : '') + '><svg viewBox="0 0 24 24"><polyline points="9 18 15 12 9 6"/></svg></button></div></div></div>'; return h }
function pgNums(c, t) { if (t <= 7) { var a = []; for (var i = 1; i <= t; i++)a.push(i); return a } var p = [1]; if (c > 3) p.push('...'); for (var j = Math.max(2, c - 1); j <= Math.min(t - 1, c + 1); j++)p.push(j); if (c < t - 2) p.push('...'); p.push(t); return p }

var ddState = { gr: { value: '', newKey: '', isOpen: false }, gv: { value: '', newKey: '', isOpen: false }, egr: { value: '', newKey: '', isOpen: false }, egv: { value: '', newKey: '', isOpen: false }, bGal: { value: '', newKey: '', isOpen: false } };
function getAlbumItems(cat, q) { var items = [], fk = {}; FM[cat].forEach(function (f) { fk[f.key] = 1; items.push({ value: cat + ':::' + f.key, name: f.name, type: 'fm' }) }); galRalyneData.concat(galRalvandraData).forEach(function (r) { if (r.folder !== cat || fk[r.album]) return; fk[r.album] = 1; items.push({ value: cat + ':::' + r.album, name: r.label || r.album, type: 'db' }) }); items.sort(function (a, b) { return a.name.toLowerCase().localeCompare(b.name.toLowerCase()) }); if (q) { var ql = q.toLowerCase(); items = items.filter(function (i) { return i.name.toLowerCase().indexOf(ql) !== -1 }) } return items }
function renderAlbumDDList(px) { var cat = px.indexOf('gv') !== -1 ? 'ralvandra' : 'ralyne'; var listId = px + 'AlbumList', searchId = px + 'AlbumSearch'; var list = document.getElementById(listId), search = document.getElementById(searchId); var q = search.value.trim(); var items = getAlbumItems(cat, q); var cv = ddState[px].value; list.innerHTML = ''; items.forEach(function (it) { var d = document.createElement('div'); d.className = 'album-dd-item'; if (it.type === 'db') d.className += ' db-item'; if (it.value === cv) d.className += ' selected'; d.innerHTML = '<span class="dd-dot"></span>' + escHtml(it.name) + (it.type === 'db' ? '<span class="dd-db-tag">DB</span>' : ''); d.dataset.value = it.value; list.appendChild(d) }); if (q) { var ex = items.some(function (i) { return i.name.toLowerCase() === q.toLowerCase() }); if (!ex) { var nd = document.createElement('div'); nd.className = 'album-dd-item new-album'; nd.dataset.value = '__new__'; nd.dataset.newKey = q; nd.textContent = '+ Buat album baru: "' + q + '"'; list.appendChild(nd) } } if (!list.children.length) list.innerHTML = '<div class="album-dd-empty">Tidak ditemukan</div>' }
function openAlbumDD(px) { var l = document.getElementById(px + 'AlbumList'), a = document.getElementById(px + 'AlbumArrow'), t = document.getElementById(px + 'AlbumTrigger'); l.classList.add('open'); a.classList.add('open'); t.classList.add('dd-open'); ddState[px].isOpen = true; renderAlbumDDList(px) }
function closeAlbumDD(px) { var l = document.getElementById(px + 'AlbumList'), a = document.getElementById(px + 'AlbumArrow'), t = document.getElementById(px + 'AlbumTrigger'); if (l) l.classList.remove('open'); if (a) a.classList.remove('open'); if (t) t.classList.remove('dd-open'); ddState[px].isOpen = false }
function setupAlbumDD(px) { var search = document.getElementById(px + 'AlbumSearch'), arrow = document.getElementById(px + 'AlbumArrow'), list = document.getElementById(px + 'AlbumList'); list.addEventListener('mousedown', function (e) { if (e.target.closest('.album-dd-item')) e.preventDefault() }); arrow.addEventListener('click', function (e) { e.stopPropagation(); if (ddState[px].isOpen) closeAlbumDD(px); else openAlbumDD(px); search.focus() }); search.addEventListener('focus', function () { this.select(); openAlbumDD(px) }); search.addEventListener('input', function () { renderAlbumDDList(px) }); list.addEventListener('click', function (e) { var it = e.target.closest('.album-dd-item'); if (!it || !it.dataset.value) return; var v = it.dataset.value; if (v === '__new__') { ddState[px].value = '__new__'; ddState[px].newKey = it.dataset.newKey || ''; search.value = ddState[px].newKey } else { ddState[px].value = v; ddState[px].newKey = ''; var f = findFolder(v); search.value = f ? f.name : it.textContent.trim() } closeAlbumDD(px); if (px === 'gr') onGalAlbumSelect('add', 'ralyne'); else if (px === 'gv') onGalAlbumSelect('add', 'ralvandra'); else if (px === 'egr') onGalAlbumSelect('edit', 'ralyne'); else if (px === 'egv') onGalAlbumSelect('edit', 'ralvandra'); else if (px === 'bGal') onBatchGalAlbumSelect() }); search.addEventListener('keydown', function (e) { if (e.key === 'Escape') { closeAlbumDD(px); search.blur() } if (e.key === 'Enter') { e.preventDefault(); var fi = list.querySelector('.album-dd-item'); if (fi) fi.click() } }); search.addEventListener('blur', function () { setTimeout(function () { if (!ddState[px].isOpen) return; closeAlbumDD(px); var tt = search.value.trim(); if (!tt) { ddState[px].value = ''; ddState[px].newKey = ''; return } var cv = ddState[px].value; if (cv && cv !== '__new__') { var f = findFolder(cv); if (f && f.name === tt) return } if (cv === '__new__' && ddState[px].newKey === tt) return; var cat = px.indexOf('gv') !== -1 ? 'ralvandra' : 'ralyne'; var all = getAlbumItems(cat, ''); var exact = all.find(function (i) { return i.name.toLowerCase() === tt.toLowerCase() }); if (exact) { ddState[px].value = exact.value; ddState[px].newKey = ''; search.value = exact.name } else { ddState[px].value = '__new__'; ddState[px].newKey = tt } }, 150) }) }
document.addEventListener('click', function (e) { ['gr', 'gv', 'egr', 'egv', 'bGal'].forEach(function (p) { var dd = document.getElementById(p + 'AlbumDD'); if (dd && !dd.contains(e.target)) closeAlbumDD(p) }) });
setupAlbumDD('gr'); setupAlbumDD('gv'); setupAlbumDD('egr'); setupAlbumDD('egv'); setupAlbumDD('bGal');
function findFolder(v) { if (!v || v === '__new__') return null; return FM_LOOKUP[v] || null }
function lockField(el) { el.classList.add('locked'); el.setAttribute('readonly', ''); el.setAttribute('tabindex', '-1'); el.style.pointerEvents = 'none'; el.style.userSelect = 'none' }
function unlockField(el) { el.classList.remove('locked'); el.removeAttribute('readonly'); el.removeAttribute('tabindex'); el.style.pointerEvents = ''; el.style.userSelect = '' }
function getNextFileNumber(cat, al) { var mx = 0; var pf = cat === 'ralyne' ? 'ralyne' : 'ralvandra'; var d = galRalyneData.concat(galRalvandraData); d.forEach(function (r) { if (r.folder === cat && r.album === al && r.src) { var fn = r.src.split('/').pop(); if (fn.toLowerCase().startsWith(pf.toLowerCase())) { var m = fn.match(/\((\d+)\)/); if (m) { var n = parseInt(m[1], 10); if (n > mx) mx = n } } } }); return mx + 1 }

function onGalAlbumSelect(mode, cat) { var px = cat === 'ralyne' ? (mode === 'add' ? 'gr' : 'egr') : (mode === 'add' ? 'gv' : 'egv'); var val = ddState[px].value; var nk = ddState[px].newKey; var f = findFolder(val); var labelEl = document.getElementById(px + 'Label'), altEl = document.getElementById(px + 'Alt'); if (val === '__new__' || !val) { unlockField(labelEl); unlockField(altEl); labelEl.value = nk || ''; altEl.value = ''; var bp = (cat === 'ralyne' ? 'Ralynee/Ralyne' : 'Ralynee/Ralvandra/') + (nk || '') + '/'; document.getElementById(px + 'BasePathWrap').style.display = ''; document.getElementById(px + 'BasePathText').textContent = bp; if (mode === 'add') { var nn = getNextFileNumber(cat, nk); document.getElementById(px + 'FileStart').value = nn; document.getElementById(px + 'FileEnd').value = nn; document.getElementById(px + 'RangeWrap').style.display = '' } document.getElementById(px + 'PathLabel').textContent = 'Filename (Multi)' } else if (f) { lockField(labelEl); lockField(altEl); labelEl.value = f.name; altEl.value = f.alt; if (f.dir) { document.getElementById(px + 'BasePathWrap').style.display = ''; document.getElementById(px + 'BasePathText').textContent = f.dir; if (mode === 'add') { var nn = getNextFileNumber(cat, val.split(':::')[1]); document.getElementById(px + 'FileStart').value = nn; document.getElementById(px + 'FileEnd').value = nn; document.getElementById(px + 'RangeWrap').style.display = '' } document.getElementById(px + 'PathLabel').textContent = 'Filename (Multi)' } else { document.getElementById(px + 'BasePathWrap').style.display = 'none'; if (mode === 'add') document.getElementById(px + 'RangeWrap').style.display = 'none'; document.getElementById(px + 'PathLabel').textContent = 'Path Foto' } } else { lockField(labelEl); lockField(altEl); labelEl.value = ''; altEl.value = ''; document.getElementById(px + 'BasePathWrap').style.display = 'none'; if (mode === 'add') document.getElementById(px + 'RangeWrap').style.display = 'none'; document.getElementById(px + 'PathLabel').textContent = 'Path Foto' } }
function generateRalyneFilenames() { var s = parseInt(document.getElementById('grFileStart').value, 10), e = parseInt(document.getElementById('grFileEnd').value, 10); if (isNaN(s) || isNaN(e) || s <= 0 || e <= 0 || s > e) { document.getElementById('grSrc').value = ''; return } var lines = []; for (var i = s; i <= e; i++)lines.push('ralyne (' + i + ').jpg'); document.getElementById('grSrc').value = lines.join('\n') }
function generateRalvandraFilenames() { var s = parseInt(document.getElementById('gvFileStart').value, 10), e = parseInt(document.getElementById('gvFileEnd').value, 10); if (isNaN(s) || isNaN(e) || s <= 0 || e <= 0 || s > e) { document.getElementById('gvSrc').value = ''; return } var lines = []; for (var i = s; i <= e; i++)lines.push('ralvandra (' + i + ').jpg'); document.getElementById('gvSrc').value = lines.join('\n') }
function onBatchGalAlbumSelect() { }

var vPage = 1, vSize = 15;
function refreshVideo() { apiGet('readVideos').then(function (d) { videoData = Array.isArray(d) ? d : []; document.getElementById('vStatTotal').textContent = videoData.length; var now = new Date(), bm = 0; videoData.forEach(function (r) { var dt = r.tanggal ? new Date(r.tanggal) : null; if (dt && dt.getMonth() === now.getMonth() && dt.getFullYear() === now.getFullYear()) bm++ }); document.getElementById('vStatBulan').textContent = bm; vPage = 1; renderVideoTable(); updateDashboardCounts() }).catch(function () { videoData = []; renderVideoTable() }) }
function renderVideoTable() { var s = (document.getElementById('searchV').value || '').toLowerCase(), f = videoData.filter(function (r) { return !s || r.judul.toLowerCase().indexOf(s) !== -1 || (r.platform || '').toLowerCase().indexOf(s) !== -1 }); var body = document.getElementById('videoBody'); if (!f.length) { body.innerHTML = '<tr class="empty-row"><td colspan="6">Belum ada video</td></tr>'; document.getElementById('videoFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(f.length / vSize)); if (vPage > tp) vPage = tp; var st = (vPage - 1) * vSize, en = Math.min(st + vSize, f.length), sh = f.slice(st, en); var h = ''; sh.forEach(function (r, i) { var linkHtml = r.link ? '<a href="' + escAttr(r.link) + '" target="_blank" class="video-link"><svg viewBox="0 0 24 24"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg> Buka</a>' : '<span style="color:var(--muted);font-size:.72rem">-</span>'; var plat = r.platform || 'Lainnya'; h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td style="font-weight:500">' + escHtml(r.judul) + '</td><td><span class="platform-badge ' + platformClass(plat) + '">' + escHtml(plat) + '</span></td><td>' + linkHtml + '</td><td>' + escHtml(r.tanggal || '-') + '</td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditV(\'' + escJS(r.id) + '\')" title="Edit"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delVideo(\'' + escJS(r.id) + '\')" title="Hapus"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h; document.getElementById('videoFooter').innerHTML = buildPgHTML(vPage, tp, f.length, st + 1, en, 'goVPage', 'setVSize', vSize) }
function goVPage(p) { vPage = p; renderVideoTable() }
function setVSize(v) { vSize = v; vPage = 1; renderVideoTable() }
function addVideo() { var btn = document.getElementById('addVBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var j = document.getElementById('vJudul').value.trim(), l = document.getElementById('vLink').value.trim(), p = document.getElementById('vPlatform').value, t = document.getElementById('vTanggal').value, d = document.getElementById('vDeskripsi').value.trim(); if (!j || !l) { toast('Judul dan link wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addVideo', judul: j, link: l, platform: p, tanggal: t, toIDDate: toIDDate(t), deskripsi: d }).then(function (r) { if (r.success) { toast('Video ditambahkan', 'success'); if (document.getElementById('quickV').checked) { document.getElementById('vJudul').value = ''; document.getElementById('vLink').value = ''; document.getElementById('vDeskripsi').value = ''; document.getElementById('vTanggal').value = todayStr() } else resetVForm(); refreshVideo() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetVForm() { document.getElementById('vJudul').value = ''; document.getElementById('vLink').value = ''; document.getElementById('vPlatform').value = 'YouTube'; document.getElementById('vTanggal').value = todayStr(); document.getElementById('vDeskripsi').value = '' }
function openEditV(id) { var r = videoData.find(function (x) { return x.id === id }); if (!r) return; editingVId = id; document.getElementById('evJudul').value = r.judul || ''; document.getElementById('evLink').value = r.link || ''; document.getElementById('evPlatform').value = r.platform || 'YouTube'; document.getElementById('evTanggal').value = fromIDDate(r.tanggal || ''); document.getElementById('evDeskripsi').value = r.deskripsi || ''; openModal('editVModal') }
function saveEditV() { var btn = document.querySelector('#editVModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editVideo', id: editingVId, judul: document.getElementById('evJudul').value.trim(), link: document.getElementById('evLink').value.trim(), platform: document.getElementById('evPlatform').value, tanggal: document.getElementById('evTanggal').value, deskripsi: document.getElementById('evDeskripsi').value.trim() }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editVModal'); refreshVideo() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delVideo(id) { openDelete('Hapus video ini?', function (btn) { apiPost({ action: 'deleteVideo', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshVideo() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

var scPage = 1, scSize = 15;
function updateScFormUI() { var tipe = document.getElementById('scTipe').value, tgl = document.getElementById('scTanggal').value, gJam = document.getElementById('scJamGroup'), gUs = document.getElementById('scUnitSongGroup'), gSo = document.getElementById('scSoGroup'), gLink = document.getElementById('scLinkGroup'), lbl = document.getElementById('scNamaLabel'), isTema = isTemaType(tipe), isPast = false; if (tgl) { var today = new Date(); today.setHours(0, 0, 0, 0); var d = new Date(tgl + 'T00:00:00'); if (d < today) isPast = true } if (isTema) lbl.textContent = 'Tema'; else lbl.textContent = 'Nama Kegiatan'; var showSoLink = isTema && !isPast; if (gSo) gSo.style.display = showSoLink ? '' : 'none'; if (gLink) gLink.style.display = showSoLink ? '' : 'none'; if (!showSoLink) { document.getElementById('scSo').value = ''; document.getElementById('scLink').value = '' } if (tipe === 'digital') { gJam.style.display = ''; gUs.style.display = 'none' } else if (isTema) { gJam.style.display = isPast ? 'none' : ''; gUs.style.display = 'none' } else { if (isPast) { gJam.style.display = 'none'; gUs.style.display = '' } else { gJam.style.display = ''; gUs.style.display = 'none' } } }
function updateEscFormUI() { var tipe = document.getElementById('escTipe').value, tgl = document.getElementById('escTanggal').value, gJam = document.getElementById('escJamGroup'), gUs = document.getElementById('escUnitSongGroup'), gSo = document.getElementById('escSoGroup'), gLink = document.getElementById('escLinkGroup'), isTema = isTemaType(tipe), isPast = false; if (tgl) { var today = new Date(); today.setHours(0, 0, 0, 0); var d = new Date(tgl + 'T00:00:00'); if (d < today) isPast = true } var showSoLink = isTema && !isPast; if (gSo) gSo.style.display = showSoLink ? '' : 'none'; if (gLink) gLink.style.display = showSoLink ? '' : 'none'; if (tipe === 'digital') { gJam.style.display = ''; gUs.style.display = 'none' } else if (isTema) { gJam.style.display = isPast ? 'none' : ''; gUs.style.display = 'none' } else { if (isPast) { gJam.style.display = 'none'; gUs.style.display = '' } else { gJam.style.display = ''; gUs.style.display = 'none' } } }
function refreshSchedule() { document.getElementById('scheduleBody').innerHTML = '<tr class="empty-row"><td colspan="8"><div class="spinner"></div><br>Memuat...</td></tr>'; apiGet('readSchedule').then(function (d) { scheduleData = Array.isArray(d) ? d : []; renderScStats(); scPage = 1; renderScheduleTable(); updateDashboardCounts() }).catch(function () { scheduleData = []; renderScheduleTable() }) }
function renderScStats() { var t = 0, the = 0, ev = 0, di = 0, co = 0, oa = 0, vc = 0, ts = 0, mg = 0; scheduleData.forEach(function (r) { t++; var tc = tipeClass(r.tipe); if (tc === 'theater') the++; else if (tc === 'event') ev++; else if (tc === 'digital') di++; else if (tc === 'concert') co++; else if (tc === 'offair') oa++; else if (tc === 'vc') vc++; else if (tc === 'two-shoot') ts++; else if (tc === 'mg') mg++ }); document.getElementById('scStatTotal').textContent = t; document.getElementById('scStatTheater').textContent = the; document.getElementById('scStatEvent').textContent = ev; document.getElementById('scStatDigital').textContent = di; document.getElementById('scStatConcert').textContent = co; document.getElementById('scStatOffair').textContent = oa; document.getElementById('scStatVc').textContent = vc; document.getElementById('scStat2shoot').textContent = ts; document.getElementById('scStatMg').textContent = mg }
function renderScheduleTable() { var s = (document.getElementById('searchSc').value || '').toLowerCase(), f = scheduleData.filter(function (r) { return !s || r.nama.toLowerCase().indexOf(s) !== -1 || r.tanggal.toLowerCase().indexOf(s) !== -1 || tipeLabel(r.tipe).toLowerCase().indexOf(s) !== -1 }); f.sort(function (a, b) { return new Date(b.tanggal || 0) - new Date(a.tanggal || 0) }); var body = document.getElementById('scheduleBody'); if (!f.length) { body.innerHTML = '<tr class="empty-row"><td colspan="8">Belum ada jadwal</td></tr>'; document.getElementById('scheduleFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(f.length / scSize)); if (scPage > tp) scPage = tp; var st = (scPage - 1) * scSize, en = Math.min(st + scSize, f.length), sh = f.slice(st, en); var h = ''; sh.forEach(function (r, i) { var tc = tipeClass(r.tipe); var isTema = isTemaType(tc); var isPast = r.tanggal ? new Date(r.tanggal + 'T00:00:00') < new Date() : false; var soLinkCell = '<td>-</td>'; if (isTema && !isPast) { var soHtml = r.so ? '<div style="font-size:.76rem;font-weight:600;color:var(--red)">Sold Out</div>' : '<div style="font-size:.68rem;font-weight:600;color:var(--green)">Tersedia</div>'; var linkHtml = r.link ? '<a href="' + escAttr(r.link) + '" target="_blank" class="buy-link"><svg viewBox="0 0 24 24"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg> Beli</a>' : '<div style="font-size:.68rem;color:var(--muted)">-</div>'; soLinkCell = '<td>' + soHtml + linkHtml + '</td>' } var jc = isPast ? (r.unitSong ? '<div class="unit-song-label">' + escHtml(r.unitSong).replace(/\n/g, '<br>') + '</div>' : '-') : escHtml(r.jam || '-'); h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td style="font-weight:500">' + escHtml(r.nama) + '</td><td><span class="type-badge ' + tc + '">' + tipeLabel(r.tipe) + '</span></td><td>' + escHtml(r.tanggal) + '</td>' + soLinkCell + '<td>' + jc + '</td><td><span class="status-dot ' + (isPast ? 'done' : 'upcoming') + '"></span>' + (isPast ? 'Selesai' : 'Mendatang') + '</td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditSc(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delSchedule(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h; document.getElementById('scheduleFooter').innerHTML = buildPgHTML(scPage, tp, f.length, st + 1, en, 'goScPage', 'setScSize', scSize) }
function goScPage(p) { scPage = p; renderScheduleTable() }
function setScSize(v) { scSize = v; scPage = 1; renderScheduleTable() }
function addSchedule() { var btn = document.getElementById('addScBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var n = document.getElementById('scNama').value.trim(), t = document.getElementById('scTipe').value, d = document.getElementById('scTanggal').value, j = document.getElementById('scJam').value, ds = document.getElementById('scDesc').value.trim(), us = document.getElementById('scUnitSong').value.trim(), so = document.getElementById('scSo').value.trim(), lk = document.getElementById('scLink').value.trim(); if (!n || !d) { toast('Nama dan tanggal wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addSchedule', nama: n, tipe: t, deskripsi: ds, tanggal: toIDDate(d), jam: j ? j + ' WIB' : '', unitSong: us, so: so, link: lk }).then(function (r) { if (r.success) { toast('Ditambahkan', 'success'); if (document.getElementById('quickSc').checked) document.getElementById('scTanggal').value = ''; else resetScForm(); refreshSchedule() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetScForm() { document.getElementById('scNama').value = ''; document.getElementById('scTipe').value = 'theater'; document.getElementById('scTanggal').value = ''; document.getElementById('scJam').value = '14:00'; document.getElementById('scUnitSong').value = ''; document.getElementById('scDesc').value = ''; document.getElementById('scSo').value = ''; document.getElementById('scLink').value = ''; updateScFormUI() }
function openEditSc(id) { var r = scheduleData.find(function (x) { return x.id === id }); if (!r) return; editingScId = id; document.getElementById('escNama').value = r.nama || ''; document.getElementById('escTipe').value = tipeClass(r.tipe); document.getElementById('escTanggal').value = fromIDDate(r.tanggal || ''); document.getElementById('escJam').value = (r.jam || '').replace(' WIB', ''); document.getElementById('escDesc').value = r.deskripsi || ''; document.getElementById('escUnitSong').value = r.unitSong || ''; document.getElementById('escSo').value = r.so || ''; document.getElementById('escLink').value = r.link || ''; updateEscFormUI(); openModal('editScModal') }
function saveEditSc() { var btn = document.querySelector('#editScModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editSchedule', id: editingScId, nama: document.getElementById('escNama').value.trim(), tipe: document.getElementById('escTipe').value, deskripsi: document.getElementById('escDesc').value.trim(), tanggal: toIDDate(document.getElementById('escTanggal').value), jam: document.getElementById('escJam').value ? document.getElementById('escJam').value + ' WIB' : '', unitSong: document.getElementById('escUnitSong').value.trim(), so: document.getElementById('escSo').value.trim(), link: document.getElementById('escLink').value.trim() }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editScModal'); refreshSchedule() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delSchedule(id) { openDelete('Hapus jadwal ini?', function (btn) { apiPost({ action: 'deleteSchedule', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshSchedule() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

var grPage = 1, grSize = 15;
function refreshGalRalyne() { apiGet('readGalleryRalyne').then(function (d) { galRalyneData = Array.isArray(d) ? d : []; var p = 0, a = {}; galRalyneData.forEach(function (f) { p += (f.images || []).length; a[f.key] = 1 }); document.getElementById('grStatTotal').textContent = p; document.getElementById('grStatAlbum').textContent = Object.keys(a).length; grPage = 1; renderGalRalyneTable(); updateDashboardCounts() }).catch(function () { galRalyneData = []; renderGalRalyneTable() }) }
function renderGalRalyneTable() { var s = (document.getElementById('searchGr').value || '').toLowerCase(), imgs = []; galRalyneData.forEach(function (f) { (f.images || []).forEach(function (img) { imgs.push({ id: f.key + ':::' + img.src, albumKey: f.key, albumLabel: f.label, src: img.src, alt: img.alt || '' }) }) }); if (s) imgs = imgs.filter(function (r) { return r.src.toLowerCase().indexOf(s) !== -1 || r.alt.toLowerCase().indexOf(s) !== -1 || r.albumLabel.toLowerCase().indexOf(s) !== -1 }); var wrap = document.getElementById('grTableWrap'); if (!imgs.length) { wrap.innerHTML = '<div style="padding:40px;text-align:center;color:var(--muted)">Belum ada foto</div>'; document.getElementById('grFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(imgs.length / grSize)); if (grPage > tp) grPage = tp; var st = (grPage - 1) * grSize, en = Math.min(st + grSize, imgs.length), sh = imgs.slice(st, en); var h = '<table><thead><tr><th>No</th><th>Preview</th><th>Album</th><th>Alt</th><th>Path</th><th>Aksi</th></tr></thead><tbody>'; sh.forEach(function (r, i) { h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td><img class="thumb" src="' + escAttr(r.src) + '" onerror="this.style.display=\'none\'"></td><td><span class="folder-badge ralyne">' + escHtml(r.albumLabel || r.albumKey) + '</span></td><td style="color:var(--muted);font-size:.76rem">' + escHtml(r.alt || '-') + '</td><td style="color:var(--muted);font-size:.72rem;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + escHtml(r.src) + '</td><td><div class="table-actions"><button class="tbl-btn del" onclick="delGalRalyne(\'' + escJS(r.albumKey) + '\',\'' + escJS(r.src) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); h += '</tbody></table>'; wrap.innerHTML = h; document.getElementById('grFooter').innerHTML = buildPgHTML(grPage, tp, imgs.length, st + 1, en, 'goGrPage', 'setGrSize', grSize) }
function goGrPage(p) { grPage = p; renderGalRalyneTable() }
function setGrSize(v) { grSize = v; grPage = 1; renderGalRalyneTable() }
function addGalRalyne() { var btn = document.getElementById('addGrBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var val = ddState.gr.value, al, la; if (val === '__new__' || !val) { al = ddState.gr.newKey.trim(); la = document.getElementById('grLabel').value.trim(); if (!al) { toast('Ketik nama folder', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } } else { al = val.split(':::')[1]; la = document.getElementById('grLabel').value.trim() } var st = document.getElementById('grSrc').value.trim(), at = document.getElementById('grAlt').value.trim(); if (!st) { toast('Path wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } var fns = st.split(/[\n,]+/).map(function (f) { return f.trim() }).filter(function (f) { return f !== '' }); var sb = document.getElementById('grBasePathText').textContent; var chain = Promise.resolve(); var hasErr = false; fns.forEach(function (fn) { var fp = sb ? sb + fn : fn; chain = chain.then(function () { return apiPost({ action: 'addGalleryRalyne', albumKey: al, albumLabel: la, src: fp, alt: at }).catch(function () { hasErr = true; return null }) }) }); chain.then(function () { if (!hasErr) toast('Berhasil', 'success'); else toast('Ada yang gagal', 'error'); if (document.getElementById('quickGr').checked) { document.getElementById('grSrc').value = ''; document.getElementById('grFileStart').value = ''; document.getElementById('grFileEnd').value = '' } else resetGrForm(); refreshGalRalyne() }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetGrForm() { ddState.gr.value = ''; ddState.gr.newKey = ''; document.getElementById('grAlbumSearch').value = ''; closeAlbumDD('gr'); lockField(document.getElementById('grLabel')); document.getElementById('grLabel').value = ''; lockField(document.getElementById('grAlt')); document.getElementById('grAlt').value = ''; document.getElementById('grSrc').value = ''; document.getElementById('grBasePathWrap').style.display = 'none'; document.getElementById('grRangeWrap').style.display = 'none' }
function delGalRalyne(key, src) { openDelete('Hapus foto ini dari album?', function (btn) { apiPost({ action: 'deleteGalleryRalyne', albumKey: key, src: src }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshGalRalyne() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

var gvPage = 1, gvSize = 15;
function refreshGalRalvandra() { apiGet('readGalleryRalvandra').then(function (d) { galRalvandraData = Array.isArray(d) ? d : []; var p = 0, a = {}; galRalvandraData.forEach(function (f) { p += (f.images || []).length; a[f.key] = 1 }); document.getElementById('gvStatTotal').textContent = p; document.getElementById('gvStatAlbum').textContent = Object.keys(a).length; gvPage = 1; renderGalRalvandraTable(); updateDashboardCounts() }).catch(function () { galRalvandraData = []; renderGalRalvandraTable() }) }
function renderGalRalvandraTable() { var s = (document.getElementById('searchGv').value || '').toLowerCase(), imgs = []; galRalvandraData.forEach(function (f) { (f.images || []).forEach(function (img) { imgs.push({ id: f.key + ':::' + img.src, albumKey: f.key, albumLabel: f.label, src: img.src, alt: img.alt || '' }) }) }); if (s) imgs = imgs.filter(function (r) { return r.src.toLowerCase().indexOf(s) !== -1 || r.alt.toLowerCase().indexOf(s) !== -1 || r.albumLabel.toLowerCase().indexOf(s) !== -1 }); var wrap = document.getElementById('gvTableWrap'); if (!imgs.length) { wrap.innerHTML = '<div style="padding:40px;text-align:center;color:var(--muted)">Belum ada foto</div>'; document.getElementById('gvFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(imgs.length / gvSize)); if (gvPage > tp) gvPage = tp; var st = (gvPage - 1) * gvSize, en = Math.min(st + gvSize, imgs.length), sh = imgs.slice(st, en); var h = '<table><thead><tr><th>No</th><th>Preview</th><th>Album</th><th>Alt</th><th>Path</th><th>Aksi</th></tr></thead><tbody>'; sh.forEach(function (r, i) { h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td><img class="thumb" src="' + escAttr(r.src) + '" onerror="this.style.display=\'none\'"></td><td><span class="folder-badge ralvandra">' + escHtml(r.albumLabel || r.albumKey) + '</span></td><td style="color:var(--muted);font-size:.76rem">' + escHtml(r.alt || '-') + '</td><td style="color:var(--muted);font-size:.72rem;max-width:180px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">' + escHtml(r.src) + '</td><td><div class="table-actions"><button class="tbl-btn del" onclick="delGalRalvandra(\'' + escJS(r.albumKey) + '\',\'' + escJS(r.src) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); h += '</tbody></table>'; wrap.innerHTML = h; document.getElementById('gvFooter').innerHTML = buildPgHTML(gvPage, tp, imgs.length, st + 1, en, 'goGvPage', 'setGvSize', gvSize) }
function goGvPage(p) { gvPage = p; renderGalRalvandraTable() }
function setGvSize(v) { gvSize = v; gvPage = 1; renderGalRalvandraTable() }
function addGalRalvandra() { var btn = document.getElementById('addGvBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var val = ddState.gv.value, al, la; if (val === '__new__' || !val) { al = ddState.gv.newKey.trim(); la = document.getElementById('gvLabel').value.trim(); if (!al) { toast('Ketik nama folder', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } } else { al = val.split(':::')[1]; la = document.getElementById('gvLabel').value.trim() } var st = document.getElementById('gvSrc').value.trim(), at = document.getElementById('gvAlt').value.trim(); if (!st) { toast('Path wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } var fns = st.split(/[\n,]+/).map(function (f) { return f.trim() }).filter(function (f) { return f !== '' }); var sb = document.getElementById('gvBasePathText').textContent; var chain = Promise.resolve(); var hasErr = false; fns.forEach(function (fn) { var fp = sb ? sb + fn : fn; chain = chain.then(function () { return apiPost({ action: 'addGalleryRalvandra', albumKey: al, albumLabel: la, src: fp, alt: at }).catch(function () { hasErr = true; return null }) }) }); chain.then(function () { if (!hasErr) toast('Berhasil', 'success'); else toast('Ada yang gagal', 'error'); if (document.getElementById('quickGv').checked) { document.getElementById('gvSrc').value = ''; document.getElementById('gvFileStart').value = ''; document.getElementById('gvFileEnd').value = '' } else resetGvForm(); refreshGalRalvandra() }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetGvForm() { ddState.gv.value = ''; ddState.gv.newKey = ''; document.getElementById('gvAlbumSearch').value = ''; closeAlbumDD('gv'); lockField(document.getElementById('gvLabel')); document.getElementById('gvLabel').value = ''; lockField(document.getElementById('gvAlt')); document.getElementById('gvAlt').value = ''; document.getElementById('gvSrc').value = ''; document.getElementById('gvBasePathWrap').style.display = 'none'; document.getElementById('gvRangeWrap').style.display = 'none' }
function delGalRalvandra(key, src) { openDelete('Hapus foto ini dari album?', function (btn) { apiPost({ action: 'deleteGalleryRalvandra', albumKey: key, src: src }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshGalRalvandra() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

function openBatchGalModal(type) { batchGalType = type; document.getElementById('batchGalTitle').textContent = 'Batch Add Foto ' + (type === 'ralyne' ? 'Ralyne' : 'Ralvandra'); ddState.bGal.value = ''; ddState.bGal.newKey = ''; document.getElementById('bGalAlbumSearch').value = ''; document.getElementById('bGalUrls').value = ''; openModal('batchGalModal') }
function submitBatchGal() { var btn = document.getElementById('batchGalBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var val = ddState.bGal.value, al, la; if (val === '__new__' || !val) { al = ddState.bGal.newKey.trim() || document.getElementById('bGalAlbumSearch').value.trim(); la = al; if (!al) { toast('Pilih atau buat folder', 'error'); btn.disabled = false; btn.textContent = 'Tambah Semua'; return } } else { al = val.split(':::')[1]; var f = findFolder(val); la = f ? f.name : al } var urls = document.getElementById('bGalUrls').value.trim().split('\n').map(function (u) { return u.trim() }).filter(function (u) { return u !== '' }); if (!urls.length) { toast('Masukkan URL foto', 'error'); btn.disabled = false; btn.textContent = 'Tambah Semua'; return } var action = batchGalType === 'ralyne' ? 'addGalleryRalyne' : 'addGalleryRalvandra'; var chain = Promise.resolve(); var ok = 0, fail = 0; urls.forEach(function (url) { chain = chain.then(function () { return apiPost({ action: action, albumKey: al, albumLabel: la, src: url, alt: la }).then(function (r) { if (r.success) ok++; else fail++ }).catch(function () { fail++ }) }) }); chain.then(function () { if (ok > 0) toast(ok + ' foto ditambahkan', 'success'); if (fail > 0) toast(fail + ' gagal', 'error'); closeModal('batchGalModal'); if (batchGalType === 'ralyne') refreshGalRalyne(); else refreshGalRalvandra() }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah Semua' }) }

var hPage = 1, hSize = 15;
function refreshHashtag() { apiGet('readHashtags').then(function (d) { hashtagData = Array.isArray(d) ? d : []; document.getElementById('hStatTotal').textContent = hashtagData.length; hPage = 1; renderHashtagTable(); updateDashboardCounts() }).catch(function () { hashtagData = []; renderHashtagTable() }) }
function renderHashtagTable() { var s = (document.getElementById('searchH').value || '').toLowerCase(), f = hashtagData.filter(function (r) { return !s || r.hashtag.toLowerCase().indexOf(s) !== -1 || (r.keterangan || '').toLowerCase().indexOf(s) !== -1 }); var body = document.getElementById('hashtagBody'); if (!f.length) { body.innerHTML = '<tr class="empty-row"><td colspan="4">Belum ada hashtag</td></tr>'; document.getElementById('hashtagFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(f.length / hSize)); if (hPage > tp) hPage = tp; var st = (hPage - 1) * hSize, en = Math.min(st + hSize, f.length), sh = f.slice(st, en); var h = ''; sh.forEach(function (r, i) { h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td><span class="hashtag-text">#' + escHtml(r.hashtag) + '</span></td><td style="font-size:.8rem;color:var(--muted)">' + escHtml(r.keterangan || '-') + '</td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditH(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delHashtag(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h; document.getElementById('hashtagFooter').innerHTML = buildPgHTML(hPage, tp, f.length, st + 1, en, 'goHPage', 'setHSize', hSize) }
function goHPage(p) { hPage = p; renderHashtagTable() }
function setHSize(v) { hSize = v; hPage = 1; renderHashtagTable() }
function cleanTag(t) { t = t.trim(); while (t.startsWith('#')) t = t.substring(1); return t.trim() }
function addHashtag() { var btn = document.getElementById('addHBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var tag = cleanTag(document.getElementById('hTag').value), desk = document.getElementById('hDesk').value.trim(); if (!tag) { toast('Hashtag wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addHashtag', hashtag: tag, keterangan: desk }).then(function (r) { if (r.success) { toast('Ditambahkan', 'success'); if (document.getElementById('quickH').checked) { document.getElementById('hTag').value = ''; document.getElementById('hDesk').value = '' } else resetHForm(); refreshHashtag() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetHForm() { document.getElementById('hTag').value = ''; document.getElementById('hDesk').value = '' }
function openEditH(id) { var r = hashtagData.find(function (x) { return x.id === id }); if (!r) return; editingHId = id; document.getElementById('ehTag').value = r.hashtag || ''; document.getElementById('ehDesk').value = r.keterangan || ''; openModal('editHModal') }
function saveEditH() { var btn = document.querySelector('#editHModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editHashtag', id: editingHId, hashtag: cleanTag(document.getElementById('ehTag').value), keterangan: document.getElementById('ehDesk').value.trim() }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editHModal'); refreshHashtag() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delHashtag(id) { openDelete('Hapus hashtag ini?', function (btn) { apiPost({ action: 'deleteHashtag', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshHashtag() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

var ffPage = 1, ffSize = 15;
function refreshFunfact() { apiGet('readFunFacts').then(function (d) { funfactData = Array.isArray(d) ? d : []; document.getElementById('ffStatTotal').textContent = funfactData.length; ffPage = 1; renderFunfactTable(); updateDashboardCounts() }).catch(function () { funfactData = []; renderFunfactTable() }) }
function renderFunfactTable() { var s = (document.getElementById('searchFf').value || '').toLowerCase(), f = funfactData.filter(function (r) { return !s || (r.text || '').toLowerCase().indexOf(s) !== -1 || (r.fact || '').toLowerCase().indexOf(s) !== -1 }); var body = document.getElementById('funfactBody'); if (!f.length) { body.innerHTML = '<tr class="empty-row"><td colspan="3">Belum ada fun fact</td></tr>'; document.getElementById('funfactFooter').innerHTML = ''; return } var tp = Math.max(1, Math.ceil(f.length / ffSize)); if (ffPage > tp) ffPage = tp; var st = (ffPage - 1) * ffSize, en = Math.min(st + ffSize, f.length), sh = f.slice(st, en); var h = ''; sh.forEach(function (r, i) { var txt = r.text || r.fact || ''; h += '<tr><td style="color:var(--muted)">' + (st + i + 1) + '</td><td>' + escHtml(txt) + '</td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditFf(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delFunfact(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h; document.getElementById('funfactFooter').innerHTML = buildPgHTML(ffPage, tp, f.length, st + 1, en, 'goFfPage', 'setFfSize', ffSize) }
function goFfPage(p) { ffPage = p; renderFunfactTable() }
function setFfSize(v) { ffSize = v; ffPage = 1; renderFunfactTable() }
function addFunfact() { var btn = document.getElementById('addFfBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var txt = document.getElementById('ffText').value.trim(); if (!txt) { toast('Teks wajib diisi', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addFunFact', text: txt }).then(function (r) { if (r.success) { toast('Ditambahkan', 'success'); if (document.getElementById('quickFf').checked) document.getElementById('ffText').value = ''; else resetFfForm(); refreshFunfact() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetFfForm() { document.getElementById('ffText').value = '' }
function openEditFf(id) { var r = funfactData.find(function (x) { return x.id === id }); if (!r) return; editingFfId = id; document.getElementById('effText').value = r.text || r.fact || ''; openModal('editFfModal') }
function saveEditFf() { var btn = document.querySelector('#editFfModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editFunFact', id: editingFfId, text: document.getElementById('effText').value.trim() }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editFfModal'); refreshFunfact() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delFunfact(id) { openDelete('Hapus fun fact ini?', function (btn) { apiPost({ action: 'deleteFunFact', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshFunfact() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

function refreshTicket() { apiGet('readTickets').then(function (d) { ticketData = Array.isArray(d) ? d : []; document.getElementById('tkStatTotal').textContent = ticketData.length; renderTicketTable(); updateDashboardCounts() }).catch(function () { ticketData = []; renderTicketTable() }) }
function renderTicketTable() { var body = document.getElementById('ticketBody'); if (!ticketData.length) { body.innerHTML = '<tr class="empty-row"><td colspan="6">Belum ada tiket</td></tr>'; return } var h = ''; ticketData.forEach(function (r, i) { var stMap = { open: 'open', limited: 'limited', sold: 'sold' }; var stLblMap = { open: 'Open', limited: 'Limited', sold: 'Sold Out' }; h += '<tr><td style="color:var(--muted)">' + (i + 1) + '</td><td style="font-weight:500">' + escHtml(r.title || '') + '</td><td><span class="type-badge video">' + escHtml(r.typeLabel || r.type || '') + '</span></td><td>' + escHtml(r.day || '') + ' ' + escHtml(r.mon || '') + '</td><td><span class="featured-badge ' + (stMap[r.status] || 'open') + '">' + (stLblMap[r.status] || r.status) + '</span></td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditTk(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delTicket(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h }
function addTicket() { var btn = document.getElementById('addTkBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var t = document.getElementById('tkTitle').value.trim(); if (!t) { toast('Judul wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addTicket', title: t, type: document.getElementById('tkType').value, typeLabel: document.getElementById('tkTypeLabel').value.trim(), day: document.getElementById('tkDay').value.trim(), mon: document.getElementById('tkMon').value.trim(), dow: document.getElementById('tkDow').value.trim(), time: document.getElementById('tkTime').value.trim(), venue: document.getElementById('tkVenue').value.trim(), price: document.getElementById('tkPrice').value.trim(), status: document.getElementById('tkStatus').value }).then(function (r) { if (r.success) { toast('Ditambahkan', 'success'); resetTkForm(); refreshTicket() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetTkForm() { ['tkTitle', 'tkTypeLabel', 'tkDay', 'tkMon', 'tkDow', 'tkTime', 'tkVenue', 'tkPrice'].forEach(function (id) { document.getElementById(id).value = '' }); document.getElementById('tkType').value = 'vc'; document.getElementById('tkStatus').value = 'open' }
function openEditTk(id) { var r = ticketData.find(function (x) { return x.id === id }); if (!r) return; editingTkId = id; document.getElementById('etkTitle').value = r.title || ''; document.getElementById('etkType').value = r.type || 'vc'; document.getElementById('etkTypeLabel').value = r.typeLabel || ''; document.getElementById('etkDay').value = r.day || ''; document.getElementById('etkMon').value = r.mon || ''; document.getElementById('etkDow').value = r.dow || ''; document.getElementById('etkTime').value = r.time || ''; document.getElementById('etkVenue').value = r.venue || ''; document.getElementById('etkPrice').value = r.price || ''; document.getElementById('etkStatus').value = r.status || 'open'; openModal('editTkModal') }
function saveEditTk() { var btn = document.querySelector('#editTkModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editTicket', id: editingTkId, title: document.getElementById('etkTitle').value.trim(), type: document.getElementById('etkType').value, typeLabel: document.getElementById('etkTypeLabel').value.trim(), day: document.getElementById('etkDay').value.trim(), mon: document.getElementById('etkMon').value.trim(), dow: document.getElementById('etkDow').value.trim(), time: document.getElementById('etkTime').value.trim(), venue: document.getElementById('etkVenue').value.trim(), price: document.getElementById('etkPrice').value.trim(), status: document.getElementById('etkStatus').value }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editTkModal'); refreshTicket() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delTicket(id) { openDelete('Hapus tiket ini?', function (btn) { apiPost({ action: 'deleteTicket', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshTicket() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

function refreshFanbase() { apiGet('readFanbase').then(function (d) { if (d && typeof d === 'object') { fanbaseData.registrationOpen = d.registrationOpen || false; fanbaseData.registrationLink = d.registrationLink || '' } document.getElementById('daftarStatusToggle').checked = fanbaseData.registrationOpen; document.getElementById('daftarLink').value = fanbaseData.registrationLink; updateDaftarLabel(); updateDashboardCounts() }).catch(function () { }) }

function refreshFaq() { apiGet('readFaq').then(function (d) { faqData = Array.isArray(d) ? d : []; document.getElementById('fqStatTotal').textContent = faqData.length; renderFaqTable(); updateDashboardCounts() }).catch(function () { faqData = []; renderFaqTable() }) }
function renderFaqTable() { var body = document.getElementById('faqBody'); if (!faqData.length) { body.innerHTML = '<tr class="empty-row"><td colspan="4">Belum ada FAQ</td></tr>'; return } var h = ''; faqData.forEach(function (r, i) { h += '<tr><td style="color:var(--muted)">' + (i + 1) + '</td><td style="font-weight:500">' + escHtml(r.q || r.pertanyaan || '') + '</td><td style="font-size:.8rem;color:var(--muted)">' + escHtml((r.a || r.jawaban || '').substring(0, 80)) + '...</td><td><div class="table-actions"><button class="tbl-btn" onclick="openEditFq(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><path d="M11 4H4a2 2 0 0 0-2 2v14a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-7"/><path d="M18.5 2.5a2.121 2.121 0 0 1 3 3L12 15l-4 1 1-4 9.5-9.5z"/></svg></button><button class="tbl-btn del" onclick="delFaq(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h }
function addFaq() { var btn = document.getElementById('addFqBtn'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; var q = document.getElementById('fqQ').value.trim(), a = document.getElementById('fqA').value.trim(); if (!q || !a) { toast('Pertanyaan dan jawaban wajib', 'error'); btn.disabled = false; btn.textContent = 'Tambah'; return } apiPost({ action: 'addFaq', q: q, a: a }).then(function (r) { if (r.success) { toast('Ditambahkan', 'success'); resetFqForm(); refreshFaq() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Tambah' }) }
function resetFqForm() { document.getElementById('fqQ').value = ''; document.getElementById('fqA').value = '' }
function openEditFq(id) { var r = faqData.find(function (x) { return x.id === id }); if (!r) return; editingFqId = id; document.getElementById('efqQ').value = r.q || r.pertanyaan || ''; document.getElementById('efqA').value = r.a || r.jawaban || ''; openModal('editFqModal') }
function saveEditFq() { var btn = document.querySelector('#editFqModal .btn-save'); if (btn.disabled) return; btn.disabled = true; btn.textContent = 'Menyimpan...'; apiPost({ action: 'editFaq', id: editingFqId, q: document.getElementById('efqQ').value.trim(), a: document.getElementById('efqA').value.trim() }).then(function (r) { if (r.success) { toast('Diupdate', 'success'); closeModal('editFqModal'); refreshFaq() } else toast('Gagal', 'error') }).catch(function () { toast('Gagal', 'error') }).finally(function () { btn.disabled = false; btn.textContent = 'Simpan' }) }
function delFaq(id) { openDelete('Hapus FAQ ini?', function (btn) { apiPost({ action: 'deleteFaq', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshFaq() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

function updateDaftarLabel() { var isOpen = document.getElementById('daftarStatusToggle').checked; var label = document.getElementById('daftarStatusLabel'); label.textContent = isOpen ? 'Buka' : 'Tutup'; label.style.color = isOpen ? 'var(--green)' : 'var(--red)' }
function savePendaftaran() { var status = document.getElementById('daftarStatusToggle').checked, link = document.getElementById('daftarLink').value.trim(); apiPost({ action: 'savePendaftaran', registrationOpen: status, registrationLink: link }).then(function (r) { if (r.success) { toast('Pengaturan pendaftaran disimpan', 'success'); fanbaseData.registrationOpen = status; fanbaseData.registrationLink = link; updateDashboardCounts() } else toast('Gagal menyimpan', 'error') }).catch(function () { toast('Gagal menyimpan', 'error') }) }

function refreshSurat() { apiGet('readWishes').then(function (d) { suratData = Array.isArray(d) ? d : []; var toxicC = suratData.filter(function (r) { return isToxic(r.pesan || r.message) }).length; document.getElementById('suStatTotal').textContent = suratData.length; document.getElementById('suStatToxic').textContent = toxicC; renderSuratTable(); updateDashboardCounts() }).catch(function () { suratData = []; renderSuratTable() }) }
function renderSuratTable() { var s = (document.getElementById('searchSu').value || '').toLowerCase(), f = suratData.filter(function (r) { return !s || (r.nama || r.name || '').toLowerCase().indexOf(s) !== -1 || (r.pesan || r.message || '').toLowerCase().indexOf(s) !== -1 }); var body = document.getElementById('suratBody'); if (!f.length) { body.innerHTML = '<tr class="empty-row"><td colspan="5">Belum ada surat</td></tr>'; return } var h = ''; f.forEach(function (r, i) { var toxic = isToxic(r.pesan || r.message); var badge = toxic ? '<span class="toxic-badge">Toxic</span>' : '<span class="safe-badge">Aman</span>'; var msg = toxic ? '<span class="toxic-text">' + escHtml(r.pesan || r.message) + '</span>' : escHtml(r.pesan || r.message); h += '<tr><td style="color:var(--muted)">' + (i + 1) + '</td><td style="font-weight:500">' + escHtml(r.nama || r.name || '-') + '</td><td style="max-width:300px;word-break:break-word;font-size:.82rem">' + msg + '</td><td>' + badge + '</td><td><div class="table-actions"><button class="tbl-btn del" onclick="delSurat(\'' + escJS(r.id) + '\')"><svg viewBox="0 0 24 24"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg></button></div></td></tr>' }); body.innerHTML = h }
function delSurat(id) { openDelete('Hapus surat ini?', function (btn) { apiPost({ action: 'deleteWish', id: id }).then(function (r) { if (r.success) { toast('Dihapus', 'success'); closeModal('deleteModal'); refreshSurat() } else { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' } }).catch(function () { toast('Gagal', 'error'); btn.disabled = false; btn.textContent = 'Hapus' }) }) }

(function () { var t = todayStr(); var aTgl = document.getElementById('vTanggal'); if (aTgl) aTgl.value = t })();